name: Compile and build all latex documents

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # taken from: https://github.com/koppor/mwe-miktex/blob/main/.github/workflows/miktex.yml#L80-L95
      - name: Install MiKTeX
        run: |
          choco install miktex --no-progress
          echo "C:\Program Files\MiKTeX\miktex\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      - name: Configure MiKTeX
        run: |
          initexmf --admin --verbose --set-config-value=[MPM]AutoInstall=1
          miktex --admin --verbose packages update-package-database
          miktex --admin --verbose packages update
          miktex --verbose packages update
          miktex --admin --verbose packages install cm-super
          miktex --admin --verbose fndb refresh
          initexmf --admin --verbose --update-fndb
          initexmf --admin --verbose --mklinks --force
          updmap --admin
          initexmf --report > miktex-report.txt

      - name: Compile and build all latex documents using Gradle
        run: ./gradlew buildAllPdfs --stacktrace

      # Commit all changed files back to the repository
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
